name: CI

on: [push, pull_request, workflow_dispatch]

# on:
#   pull_request:
#   push:
#     branches:
#       - master
#       - develop
#       - bugfix/**
#       - feature/**
#       - fix/**
#       - pr/**

env:
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: gcc-11
            cxxstd: "17,20"
            os: ubuntu-20.04
            install: g++-11
          - toolset: gcc-12
            cxxstd: "17,20"
            os: ubuntu-22.04
            install: g++-12
          - toolset: gcc-13
            cxxstd: "17,20"
            os: ubuntu-latest
            container: ubuntu:23.04
            install: g++-13
          - toolset: clang
            compiler: clang++-13
            cxxstd: "17,20"
            os: ubuntu-22.04
            install: clang-13
          - toolset: clang
            compiler: clang++-14
            cxxstd: "17,20"
            os: ubuntu-22.04
            install: clang-14
          - toolset: clang
            compiler: clang++-15
            cxxstd: "17,20"
            os: ubuntu-22.04
            install: clang-15
          - toolset: clang
            compiler: clang++-16
            cxxstd: "17,20"
            os: ubuntu-latest
            container: ubuntu:23.04
            install: clang-16
          - toolset: clang
            cxxstd: "17,20"
            os: macos-11
          - toolset: clang
            cxxstd: "17,20"
            os: macos-12
          - toolset: clang
            cxxstd: "17,20"
            os: macos-13

    runs-on: ${{matrix.os}}
    container: ${{matrix.container}}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Setup container environment
        if: matrix.container
        run: |
          apt-get update
          apt-get -y install sudo python3 git g++

      - name: Install packages
        if: matrix.install
        run: |
          sudo apt-get update
          sudo apt-get -y install ${{matrix.install}}

      - name: Setup Boost
        run: |
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          LIBRARY=${GITHUB_REPOSITORY#*/}
          echo LIBRARY: $LIBRARY
          echo "LIBRARY=$LIBRARY" >> $GITHUB_ENV
          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
          echo GITHUB_REF: $GITHUB_REF
          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
          REF=${REF#refs/heads/}
          echo REF: $REF
          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
          echo BOOST_BRANCH: $BOOST_BRANCH
          cd ..
          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          cp -r $GITHUB_WORKSPACE/* libs/$LIBRARY
          git submodule update --init tools/boostdep
          python3 tools/boostdep/depinst/depinst.py --git_args "--jobs 3" $LIBRARY
          ./bootstrap.sh
          ./b2 -d0 headers

      - name: Create user-config.jam
        if: matrix.compiler
        run: |
          echo "using ${{matrix.toolset}} : : ${{matrix.compiler}} ;" > ~/user-config.jam

      - name: Run tests
        run: |
          cd ../boost-root
          ./b2 -j3 libs/$LIBRARY/test toolset=${{matrix.toolset}} cxxstd=${{matrix.cxxstd}} variant=debug,release
